; Insomnia Launcher — Inno Setup script
;
; Build windows installer:
;   1. Build the exe first  ->  build_windows.bat   (produces \dist\InsomniaLauncher.exe)
;   2. Make installer        ->  build_windows_installer.bat (needs Inno Setup 6+, ISCC in PATH)
;
; The installer unpacks everything into the user's %LOCALAPPDATA% (no admin needed)
; and creates a Start-menu shortcut + optional desktop icon. Your library DB,
; Steam API key and settings live under %LOCALAPPDATA%\Insomnia Launcher and are
; never touched on upgrades.

#ifndef AppName
  #define AppName "Insomnia Launcher"
#endif
#ifndef AppVersion
  #define AppVersion "0.1.0"
#endif
#ifndef AppId
  #define AppId "91A2C4D9-C76A-49DE-B55C-D19B0BED6F8A"
#endif
#ifndef SourceExe
  #define SourceExe "..\dist\InsomniaLauncher.exe"
#endif
#ifndef SourceIcon
  #define SourceIcon "..\ui\assets\icon.ico"
#endif

[Setup]
AppId={{#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher=Insomnia Dev
AppPublisherURL=https://github.com/xyzmsl/Insomnia-Launcher
AppSupportURL=https://github.com/xyzmsl/Insomnia-Launcher/releases
DefaultDirName={localappdata}\Insomnia Launcher
DisableProgramGroupPage=yes
DefaultGroupName={#AppName}
OutputDir=..\dist
OutputBaseFilename=InsomniaLauncherSetup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\InsomniaLauncher.exe
PrivilegesRequired=lowest
ArchitecturesAllowed=x64 compat
ArchitecturesInstallIn64BitMode=x64
CloseApplications=yes

[Files]
Source: {#SourceExe}; DestDir: {app}; Flags: ignoreversion
; Icon regenerated by build_windows_installer.bat; fallback silently if absent.
#if FileExists(SourceIcon)
Source: {#SourceIcon}; DestDir: {app}
#endif

[Icons]
Name: "{userprograms}\{#AppName}"; Filename: "{app}\InsomniaLauncher.exe"; WorkingDir: "{app}"; Comment: "Launch Insomnia Launcher"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\InsomniaLauncher.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"

[Run]
Filename: "{app}\InsomniaLauncher.exe"; Description: "Launch {#AppName} now"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove the user data dir on uninstall (games themselves are never touched).
Type: filesandordirs; Name: "{localappdata}\Insomnia Launcher\data"
